### ISSUE TITLE
Npm repo publish

### ISSUE THREAD

**Issue by HollyPony** [punkave/apostrophe-override-options#4]
Hi, could you publish the package on npm repo ? Currently I see nothing : https://www.npmjs.com/search?q=apostrophe-override-options 🙈 .

Awaiting that I'll use the github branch directly

Have a good day !

**Comment by boutell** [comment]
Hi Arthur, yes this is documented, please see the comments in DGAD, you must use it from git and with the git master of apostrophe too for now, I will notify on the ticket in DGAD when both are npm published.
